def on_forever():
    pins.digital_write_pin(DigitalPin.P1, 1)
    led.plot(0, 4)
    basic.pause(100)
    pins.digital_write_pin(DigitalPin.P1, 0)
    led.unplot(0, 4)
    basic.pause(900)
    led.plot(0, 4)
    basic.pause(100)
    led.unplot(0, 4)
    led.plot(1, 4)
    led.plot(1, 3)
    led.plot(0, 3)
    basic.pause(100)
    led.unplot(1, 4)
    led.unplot(1, 3)
    led.unplot(0, 3)
    led.plot(0, 2)
    led.plot(1, 2)
    led.plot(2, 3)
    led.plot(2, 4)
    basic.pause(100)
    led.unplot(0, 2)
    led.unplot(1, 2)
    led.unplot(2, 3)
    led.unplot(2, 4)
    led.plot(0, 1)
    led.plot(1, 1)
    led.plot(2, 1)
    led.plot(3, 2)
    led.plot(3, 3)
    led.plot(3, 4)
    basic.pause(100)
    led.unplot(0, 1)
    led.unplot(1, 1)
    led.unplot(2, 1)
    led.unplot(3, 2)
    led.unplot(3, 3)
    led.unplot(3, 4)
    basic.pause(600)
basic.forever(on_forever)

def on_forever2():
    pass
basic.forever(on_forever2)
